[tool.black]

line-length = 88
preview = true

[tool.ruff]

# Same as Black.
line-length = 88

lint.select = ["A", "B", "BLE", "C4", "C90", "E", "F", "I", "PIE", "Q", "RSE", "RUF", "UP", "YTT", "SIM", "PTH"]
# "PLR" need to understand more
# "C90" McCabe complexity

# These rules are redundant with black use and ruff format
# "RUF{001,002}" warns about ambiguous Unicode for curly quotes
lint.ignore = ["E501", "Q000", "Q001", "Q002", "Q003", "RUF001", "RUF002"]
unfixable = ["F401"]


# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "_old",
]

# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.mccabe] # enabled via "C90" above
max-complexity = 10

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-r a -q --doctest-modules"
testpaths = [
    "biblio", "formats", "tests"
]
filterwarnings = "ignore::DeprecationWarning"
enable_assertion_pass_hook = true

[tool.pyright]
reportMissingImports = false
reportMissingTypeStubs = false
pythonVersion = '3.12'
